@import gg.jte.Content

@param Content content

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Анализатор страниц</title>

    <link href="/css/main.css" rel="stylesheet">
</head>

<body>
    <nav>
        <!-- Навигацию добавишь позже -->
    </nav>

    <main class="container mx-auto px-4 py-10">
        ${content}
    </main>
</body>
</html>